/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BrewdogWidget {
        "food": string;
    }
}
declare global {
    interface HTMLBrewdogWidgetElement extends Components.BrewdogWidget, HTMLStencilElement {
    }
    var HTMLBrewdogWidgetElement: {
        prototype: HTMLBrewdogWidgetElement;
        new (): HTMLBrewdogWidgetElement;
    };
    interface HTMLElementTagNameMap {
        "brewdog-widget": HTMLBrewdogWidgetElement;
    }
}
declare namespace LocalJSX {
    interface BrewdogWidget {
        "food"?: string;
    }
    interface IntrinsicElements {
        "brewdog-widget": BrewdogWidget;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "brewdog-widget": LocalJSX.BrewdogWidget & JSXBase.HTMLAttributes<HTMLBrewdogWidgetElement>;
        }
    }
}
